name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy tts to server
        run: |
          docker network ls | grep reverse-proxy > /dev/null || docker network create --driver bridge reverse-proxy
          docker compose down -v || true
          docker compose build
          docker compose up -d